from __future__ import annotations

# Source-of-truth public analysis report/response limits. Keep these finite so a
# schema-valid analysis response can be buffered safely by both the API and UI.
REPORT_REQUIRED_TEXT_MAX_CHARS = 4_000
HYPOTHESIS_STATEMENT_MAX_CHARS = 2_000
ALTERNATIVE_HYPOTHESES_MAX = 8
HYPOTHESIS_EVIDENCE_REFS_MAX = 16
REPORT_EVIDENCE_MAX = 64
EVIDENCE_EXCERPT_MAX_CHARS = 8_192
EVIDENCE_EXCERPT_MAX_BYTES = 32 * 1024
EVIDENCE_EXPLANATION_MAX_CHARS = 1_500
IMPACTED_FILES_MAX = 32
IMPACTED_FILE_EXPLANATION_MAX_CHARS = 1_500
IMPLEMENTATION_STEPS_MAX = 32
IMPLEMENTATION_STEP_MAX_CHARS = 1_500
PROPOSED_TESTS_MAX = 32
PROPOSED_TEST_NAME_MAX_CHARS = 256
PROPOSED_TEST_DESCRIPTION_MAX_CHARS = 1_500
UNCERTAINTIES_MAX = 32
UNCERTAINTY_MAX_CHARS = 1_500
REPORT_SERIALIZED_MAX_BYTES = 1024 * 1024
PREVIOUS_REPORT_HISTORY_MAX = 1
ANALYSIS_RESPONSE_MAX_BYTES = 3 * 1024 * 1024

FRONTEND_LIMITS: dict[str, int] = {
    "REPORT_REQUIRED_TEXT_MAX_CHARS": REPORT_REQUIRED_TEXT_MAX_CHARS,
    "HYPOTHESIS_STATEMENT_MAX_CHARS": HYPOTHESIS_STATEMENT_MAX_CHARS,
    "ALTERNATIVE_HYPOTHESES_MAX": ALTERNATIVE_HYPOTHESES_MAX,
    "HYPOTHESIS_EVIDENCE_REFS_MAX": HYPOTHESIS_EVIDENCE_REFS_MAX,
    "REPORT_EVIDENCE_MAX": REPORT_EVIDENCE_MAX,
    "EVIDENCE_EXCERPT_MAX_CHARS": EVIDENCE_EXCERPT_MAX_CHARS,
    "EVIDENCE_EXCERPT_MAX_BYTES": EVIDENCE_EXCERPT_MAX_BYTES,
    "EVIDENCE_EXPLANATION_MAX_CHARS": EVIDENCE_EXPLANATION_MAX_CHARS,
    "IMPACTED_FILES_MAX": IMPACTED_FILES_MAX,
    "IMPACTED_FILE_EXPLANATION_MAX_CHARS": IMPACTED_FILE_EXPLANATION_MAX_CHARS,
    "IMPLEMENTATION_STEPS_MAX": IMPLEMENTATION_STEPS_MAX,
    "IMPLEMENTATION_STEP_MAX_CHARS": IMPLEMENTATION_STEP_MAX_CHARS,
    "PROPOSED_TESTS_MAX": PROPOSED_TESTS_MAX,
    "PROPOSED_TEST_NAME_MAX_CHARS": PROPOSED_TEST_NAME_MAX_CHARS,
    "PROPOSED_TEST_DESCRIPTION_MAX_CHARS": PROPOSED_TEST_DESCRIPTION_MAX_CHARS,
    "UNCERTAINTIES_MAX": UNCERTAINTIES_MAX,
    "UNCERTAINTY_MAX_CHARS": UNCERTAINTY_MAX_CHARS,
    "REPORT_SERIALIZED_MAX_BYTES": REPORT_SERIALIZED_MAX_BYTES,
    "PREVIOUS_REPORT_HISTORY_MAX": PREVIOUS_REPORT_HISTORY_MAX,
    "ANALYSIS_RESPONSE_MAX_BYTES": ANALYSIS_RESPONSE_MAX_BYTES,
}
